"use client"

import { Cell, Pie, PieChart } from "recharts"

import type { SeverityLevel, Slices } from "@/lib/types"

import {
  ChartConfig,
  ChartContainer,
  ChartTooltip,
  ChartTooltipContent,
} from "@/components/ui/chart"

interface ZkvmPieChartProps {
  slices: Slices
  className?: string
}

const SEVERITY_COLORS: Record<SeverityLevel | "none", string> = {
  green: "hsl(var(--level-best))",
  yellow: "hsl(var(--level-middle))",
  red: "hsl(var(--level-worst))",
  none: "hsl(var(--muted-foreground))",
}

const METRIC_INFO: {
  label: string
  description: string
  statusLabels: Record<SeverityLevel | "none", string>
}[] = [
  {
    label: "proof size",
    description:
      "the size of the proof generated by this zkVM, measured in kilobytes",
    statusLabels: {
      red: "> 600 KiB",
      yellow: "≤ 600 KiB",
      green: "≤ 300 KiB",
      none: "no data",
    },
  },
  {
    label: "soundness",
    description:
      "the proof system security of the zkVM measured in bits, as computed by soundcalc",
    statusLabels: {
      red: "< 100-bit, or not integrated",
      yellow: "≥ 100-bit provable",
      green: "≥ 128-bit provable",
      none: "no data",
    },
  },
  {
    label: "quantum security",
    description:
      "resistance to attacks by quantum computers, hash-based is PQ-secure and indicates ≥ 64 bits of QROM-provable security.",
    statusLabels: {
      red: "pre-quantum components",
      yellow: "",
      green: "hashes / lattices",
      none: "no data",
    },
  },
  {
    label: "bounties",
    description: "maximum bounty amount offered for critical vulnerabilities",
    statusLabels: {
      red: "< $64k",
      yellow: "≥ $64k",
      green: "≥ $1M",
      none: "no data",
    },
  },
  {
    label: "EVM STF bytecode",
    description:
      "level of assurance provided by the EVM STF bytecode, based on audit status",
    statusLabels: {
      red: "not fully audited",
      yellow: "fully audited",
      green: "formally verified",
      none: "no data",
    },
  },
  {
    label: "implementation",
    description:
      "level of assurance provided by the zkVM implementation, based on audit status",
    statusLabels: {
      red: "not fully audited",
      yellow: "fully audited",
      green: "formally verified",
      none: "no data",
    },
  },
  {
    label: "verification time",
    description: "time to verify a single block, tracked in real time",
    statusLabels: {
      red: "≥ 16ms",
      yellow: "< 16ms",
      green: "< 1ms",
      none: "no data",
    },
  },
]

interface ZkvmPieChartLegendProps {
  slices: Slices
  className?: string
}

export function ZkvmPieChartLegend({
  slices,
  className,
}: ZkvmPieChartLegendProps) {
  const rightColumnIndices = [0, 1, 2]
  const leftColumnIndices = [6, 5, 4]
  const bottomColumnIndices = [3]

  const renderItem = (index: number) => (
    <div key={index} className="flex items-center gap-2">
      <div
        className="size-2 shrink-0 rounded-full"
        style={{
          backgroundColor: SEVERITY_COLORS[slices[index]?.level ?? "none"],
        }}
      />
      <span className="text-muted-foreground">{METRIC_INFO[index].label}</span>
    </div>
  )

  return (
    <div
      className={`flex flex-col items-center gap-x-4 gap-y-1 text-xs ${className}`}
    >
      <div className="flex gap-x-4">
        <div className="flex flex-col gap-y-1">
          {leftColumnIndices.map(renderItem)}
        </div>
        <div className="flex flex-col gap-y-1">
          {rightColumnIndices.map(renderItem)}
        </div>
      </div>
      <div className="flex flex-col gap-y-1">
        {bottomColumnIndices.map(renderItem)}
      </div>
    </div>
  )
}

export function ZkvmPieChart({ slices, className }: ZkvmPieChartProps) {
  const data = slices.map((slice, index) => ({
    name: `metric-${index}`,
    label: METRIC_INFO[index].label,
    description: METRIC_INFO[index].description,
    status: METRIC_INFO[index].statusLabels[slice.level ?? "none"],
    value: 1,
    fill: SEVERITY_COLORS[slice.level ?? "none"],
  }))

  const chartConfig = slices.reduce(
    (acc, slice, index) => {
      acc[`metric-${index}`] = {
        label: METRIC_INFO[index].label,
        color: SEVERITY_COLORS[slice.level ?? "none"],
      }
      return acc
    },
    { value: { label: "metric" } } as ChartConfig
  )

  return (
    <ChartContainer config={chartConfig} className={className}>
      <PieChart>
        <ChartTooltip
          content={
            <ChartTooltipContent
              formatter={(_value, _name, item) => (
                <div className="flex min-w-[250px] flex-col gap-1 p-2 text-sm">
                  <span className="font-medium">{item.payload.label}</span>
                  <span
                    className="font-medium"
                    style={{ color: item.payload.fill }}
                  >
                    {item.payload.status}
                  </span>

                  <span className="text-muted-foreground">
                    {item.payload.description}
                  </span>
                </div>
              )}
              hideLabel
            />
          }
        />
        <Pie
          data={data}
          dataKey="value"
          nameKey="name"
          cx="50%"
          cy="50%"
          innerRadius={0}
          outerRadius="90%"
          strokeWidth={2}
          stroke="hsl(var(--background))"
          startAngle={90}
          endAngle={-270}
        >
          {data.map((entry, index) => (
            <Cell key={`cell-${index}`} fill={entry.fill} />
          ))}
        </Pie>
      </PieChart>
    </ChartContainer>
  )
}
