export const SITE_NAME = "EthProofs"
export const SITE_DESCRIPTION = "Building a fully SNARKed Ethereum"
export const SITE_URL = "https://ethproofs.org"
export const SITE_PREVIEW_URL = "http://ethproofs.netlify.app"
export const SITE_REPO_URL = "https://github.com/ethproofs/ethproofs"
