import type { ClusterDetails } from "./types"

const commonDetails = {
  clusterVersionDate: new Date().toISOString(),
  team: {
    id: "1",
    name: "Team A",
    logoUrl: "",
  },
  zkvm: {
    id: 1,
    name: "Zkvm A",
  },
  isOpenSource: true,
  isMultiMachine: true,
  versionDate: new Date().toISOString(),
  avgCost: 100,
  avgTime: 1000000,
}

export const demoClusterDetails: ClusterDetails[] = [
  {
    id: "1",
    name: "Cluster A",
    ...commonDetails,
    machines: [
      {
        id: 1,
        cpuModel: "Machine A1",
        gpuModels: ["GPU A1"],
        gpuCount: [4],
        gpuRam: [8 * 2 ** 30],
        cpuRam: 8 * 2 ** 30,
        cpuCount: 1,
        count: 1,
      },
      {
        id: 2,
        cpuModel: "Machine A2",
        gpuModels: ["GPU A2"],
        gpuCount: [8],
        gpuRam: [16 * 2 ** 30],
        cpuRam: 16 * 2 ** 30,
        cpuCount: 1,
        count: 1,
      },
    ],
  },
  {
    id: "2",
    name: "Cluster B",
    ...commonDetails,
    machines: [
      {
        id: 3,
        cpuModel: "Machine B1",
        gpuModels: ["GPU B1"],
        gpuCount: [4],
        gpuRam: [32 * 2 ** 30],
        cpuRam: 32 * 2 ** 30,
        cpuCount: 1,
        count: 1,
      },
      {
        id: 4,
        cpuModel: "Machine B2",
        gpuModels: ["GPU B2"],
        gpuCount: [8],
        gpuRam: [24 * 2 ** 30],
        cpuRam: 24 * 2 ** 30,
        cpuCount: 1,
        count: 1,
      },
    ],
  },
  {
    id: "3",
    name: "Cluster C",
    ...commonDetails,
    machines: [
      {
        id: 5,
        cpuModel: "Machine C1",
        gpuModels: ["GPU C1"],
        gpuCount: [4],
        gpuRam: [12 * 2 ** 30],
        cpuRam: 12 * 2 ** 30,
        cpuCount: 1,
        count: 1,
      },
      {
        id: 6,
        cpuModel: "Machine C2",
        gpuModels: ["GPU C2"],
        gpuCount: [8],
        gpuRam: [16 * 2 ** 30],
        cpuRam: 16 * 2 ** 30,
        cpuCount: 1,
        count: 1,
      },
    ],
  },
  {
    id: "4",
    name: "Cluster D",
    ...commonDetails,
    machines: [
      {
        id: 7,
        cpuModel: "Machine D1",
        gpuModels: ["GPU D1"],
        gpuCount: [4],
        gpuRam: [4 * 2 ** 30],
        cpuRam: 4 * 2 ** 30,
        cpuCount: 1,
        count: 1,
      },
      {
        id: 8,
        cpuModel: "Machine D2",
        gpuModels: ["GPU D2"],
        gpuCount: [8],
        gpuRam: [8 * 2 ** 30],
        cpuRam: 8 * 2 ** 30,
        cpuCount: 1,
        count: 1,
      },
    ],
  },
  {
    id: "5",
    name: "Cluster E",
    ...commonDetails,
    machines: [
      {
        id: 9,
        cpuModel: "Machine E1",
        gpuModels: ["GPU E1"],
        gpuCount: [1],
        gpuRam: [2 * 2 ** 30],
        cpuRam: 2 * 2 ** 30,
        cpuCount: 1,
        count: 1,
      },
      {
        id: 10,
        cpuModel: "Machine E2",
        gpuModels: ["GPU E2"],
        gpuCount: [1],
        gpuRam: [2 * 2 ** 30],
        cpuRam: 2 * 2 ** 30,
        cpuCount: 1,
        count: 1,
      },
    ],
  },
  {
    id: "6",
    name: "Cluster F",
    ...commonDetails,
    machines: [
      {
        id: 11,
        cpuModel: "Machine F1",
        gpuModels: ["GPU F1"],
        gpuCount: [16],
        gpuRam: [64 * 2 ** 30],
        cpuRam: 64 * 2 ** 30,
        cpuCount: 1,
        count: 1,
      },
      {
        id: 12,
        cpuModel: "Machine F2",
        gpuModels: ["GPU F2"],
        gpuCount: [16],
        gpuRam: [48 * 2 ** 30],
        cpuRam: 48 * 2 ** 30,
        cpuCount: 1,
        count: 1,
      },
    ],
  },
  {
    id: "7",
    name: "Cluster G",
    ...commonDetails,
    machines: [
      {
        id: 13,
        cpuModel: "Machine G1",
        gpuModels: ["GPU G1"],
        gpuCount: [32],
        gpuRam: [128 * 2 ** 30],
        cpuRam: 128 * 2 ** 30,
        cpuCount: 1,
        count: 1,
      },
      {
        id: 14,
        cpuModel: "Machine G2",
        gpuModels: ["GPU G2"],
        gpuCount: [32],
        gpuRam: [96 * 2 ** 30],
        cpuRam: 96 * 2 ** 30,
        cpuCount: 1,
        count: 1,
      },
    ],
  },
  {
    id: "8",
    name: "Cluster H",
    ...commonDetails,
    machines: [
      {
        id: 15,
        cpuModel: "Machine H1",
        gpuModels: ["GPU H1"],
        gpuCount: [8],
        gpuRam: [16 * 2 ** 30],
        cpuRam: 16 * 2 ** 30,
        cpuCount: 1,
        count: 1,
      },
      {
        id: 16,
        cpuModel: "Machine H2",
        gpuModels: ["GPU H2"],
        gpuCount: [8],
        gpuRam: [16 * 2 ** 30],
        cpuRam: 16 * 2 ** 30,
        cpuCount: 1,
        count: 1,
      },
    ],
  },
  {
    id: "9",
    name: "Cluster I",
    ...commonDetails,
    machines: [
      {
        id: 17,
        cpuModel: "Machine I1",
        gpuModels: ["GPU I1"],
        gpuCount: [12],
        gpuRam: [24 * 2 ** 30],
        cpuRam: 24 * 2 ** 30,
        cpuCount: 1,
        count: 1,
      },
      {
        id: 18,
        cpuModel: "Machine I2",
        gpuModels: ["GPU I2"],
        gpuCount: [16],
        gpuRam: [32 * 2 ** 30],
        cpuRam: 32 * 2 ** 30,
        cpuCount: 1,
        count: 1,
      },
    ],
  },
  {
    id: "10",
    name: "Cluster J",
    ...commonDetails,
    machines: [
      {
        id: 19,
        cpuModel: "Machine J1",
        gpuModels: ["GPU J1"],
        gpuCount: [4],
        gpuRam: [8 * 2 ** 30],
        cpuRam: 8 * 2 ** 30,
        cpuCount: 1,
        count: 1,
      },
      {
        id: 20,
        cpuModel: "Machine J2",
        gpuModels: ["GPU J2"],
        gpuCount: [6],
        gpuRam: [12 * 2 ** 30],
        cpuRam: 12 * 2 ** 30,
        cpuCount: 1,
        count: 1,
      },
    ],
  },
].map((cluster, idx) => ({
  ...cluster,
  zkvm: {
    ...cluster.zkvm,
    slug: "zk" + idx,
  },
}))
