import type { Metadata } from "next"
import Image from "next/image"
import { notFound } from "next/navigation"

import type { Metric } from "@/lib/types"

import LearnMore from "@/components/LearnMore"
import ArrowDown from "@/components/svgs/arrow-down.svg"
import BlockLarge from "@/components/svgs/block-large.svg"
import BookOpen from "@/components/svgs/book-open.svg"
import Clock from "@/components/svgs/clock.svg"
import Copy from "@/components/svgs/copy.svg"
import Cpu from "@/components/svgs/cpu.svg"
import DollarSign from "@/components/svgs/dollar-sign.svg"
import Hash from "@/components/svgs/hash.svg"
import Layers from "@/components/svgs/layers.svg"
import ProofCircle from "@/components/svgs/proof-circle.svg"
import TrendingUp from "@/components/svgs/trending-up.svg"
import { Button } from "@/components/ui/button"
import {
  HeroBody,
  HeroDivider,
  HeroItem,
  HeroItemLabel,
  HeroSection,
  HeroTitle,
} from "@/components/ui/hero"
import {
  MetricBox,
  MetricInfo,
  MetricLabel,
  MetricValue,
} from "@/components/ui/metric"

import { timestampToEpoch, timestampToSlot } from "@/lib/beaconchain"
import { intervalToSeconds, renderTimestamp } from "@/lib/date"
import { getMetadata } from "@/lib/metadata"
import { formatNumber } from "@/lib/number"
import { getProofsAvgLatency, proofsTotalCostPerMegaGas } from "@/lib/proofs"
import { createClient } from "@/utils/supabase/client"

type BlockDetailsPageProps = {
  params: Promise<{ block: number }>
}

export async function generateMetadata({
  params,
}: BlockDetailsPageProps): Promise<Metadata> {
  const { block } = await params
  return getMetadata({ title: `Block ${block}` }) // TODO: Confirm number formatting
}

export default async function BlockDetailsPage({
  params,
}: BlockDetailsPageProps) {
  const { block } = await params

  const supabase = createClient()

  const { data, error } = await supabase
    .from("blocks")
    .select("*, proofs(*)")
    .eq("block_number", block)
    .single()

  const { data: machines } = await supabase.from("prover_machines").select("*")

  if (!data || error || !machines) notFound()

  const getProverLogoSrc = (machine_id: number) => {
    const machine = machines.find((m) => m.machine_id === machine_id)
    if (!machine?.logo_url) return ""
    return machine.logo_url
  }

  const { timestamp, gas_used, transaction_count, proofs, hash } = data

  // TODO: Dummy data, get block size data
  const size = 32735
  const dummyNumber = 60420

  // TODO: Add proper descriptions
  const performanceItems: Metric[] = [
    {
      label: "Total proofs",
      description: "The total number of proofs generated by this prover.",
      value: formatNumber(proofs.length),
    },
    {
      label: "Avg latency",
      description: "The average time it takes to generate a proof.",
      value: formatNumber(getProofsAvgLatency(proofs), {
        style: "unit",
        unit: "second",
        unitDisplay: "narrow",
        maximumFractionDigits: 0,
      }),
    },
    {
      label: "Gas used",
      description: "The total gas used to generate all proofs.",
      value: formatNumber(gas_used),
    },
    {
      label: "Transaction count",
      description: "The total number of transactions in this block.",
      value: formatNumber(transaction_count),
    },
  ]

  const blockFeeMetrics: Metric[] = [
    {
      label: "total fees",
      description: "The total fees collected in this block.",
      value: formatNumber(dummyNumber),
    },
    {
      label: "avg cost / proof",
      description: "The average cost of generating a proof.",
      value: formatNumber(dummyNumber),
    },
    {
      label: "cost / mega gas",
      description: "The cost of generating a proof per million gas.",
      value: proofsTotalCostPerMegaGas(proofs, gas_used),
    },
    {
      label: "cost / mega cycle",
      description: "The cost of generating a proof per million cycles.",
      value: formatNumber(dummyNumber),
    },
    {
      label: "cost / transaction",
      description: "The cost of generating a proof per transaction.",
      value: formatNumber(dummyNumber),
    },
  ]

  return (
    <div className="space-y-20">
      <HeroSection>
        <HeroTitle>
          <BlockLarge className="text-6xl text-primary" />
          <h1 className="font-mono">
            <p className="text-sm font-normal md:text-lg">Block Height</p>
            <p className="text-3xl font-semibold">
              {/* {formatNumber(block)} */}
              {/* TODO: Confirm number formatting for block height, slot, epoch, etc */}
              {block}
            </p>
          </h1>
        </HeroTitle>

        <HeroDivider />

        <HeroBody>
          <HeroItem>
            <HeroItemLabel>
              <Clock /> Time Stamp
            </HeroItemLabel>
            {renderTimestamp(timestamp)}
          </HeroItem>

          <div className="grid grid-cols-3 gap-6">
            <HeroItem>
              <HeroItemLabel>
                <Cpu /> Size
              </HeroItemLabel>
              {formatNumber(size)} bytes
            </HeroItem>

            <HeroItem>
              <HeroItemLabel>
                <Layers /> Slot
              </HeroItemLabel>
              {formatNumber(timestampToSlot(timestamp))}
            </HeroItem>

            <HeroItem>
              <HeroItemLabel>
                <BookOpen /> Epoch
              </HeroItemLabel>
              {formatNumber(timestampToEpoch(timestamp))}
            </HeroItem>
          </div>

          <HeroItem>
            <HeroItemLabel>
              <Hash /> Hash
            </HeroItemLabel>
            <div className="flex gap-2">
              <div className="max-w-[min(theme.80 truncate">{hash}</div>
              {/* TODO: Implement useClipboard */}
              <Button size="icon" variant="ghost" className="text-primary-dark">
                <Copy />
              </Button>
            </div>
          </HeroItem>
        </HeroBody>
      </HeroSection>

      <div className="space-y-8">
        <section>
          <h2 className="flex items-center gap-2 text-lg font-normal text-primary">
            <TrendingUp /> Zero-knowledge proofs
          </h2>
          <div className="flex flex-wrap gap-x-8">
            {performanceItems.map(({ label, description, value }) => (
              <MetricBox key={label}>
                <MetricLabel>
                  {label}
                  <MetricInfo>{description}</MetricInfo>
                </MetricLabel>
                <MetricValue>{value}</MetricValue>
              </MetricBox>
            ))}
          </div>
        </section>

        <section>
          <h2 className="flex items-center gap-2 text-lg font-normal text-primary">
            <DollarSign /> Block fees
          </h2>
          <div className="flex flex-wrap gap-x-8">
            {blockFeeMetrics.map(({ label, description, value }) => (
              <MetricBox key={label}>
                <MetricLabel>
                  {label}
                  <MetricInfo>{description}</MetricInfo>
                </MetricLabel>
                <MetricValue>{value}</MetricValue>
              </MetricBox>
            ))}
          </div>
        </section>
      </div>

      <section>
        <h2 className="flex items-center gap-2 text-lg font-normal text-primary">
          <ProofCircle /> Proofs
        </h2>

        {proofs.map(
          ({
            proof_id,
            prover_duration,
            prover_machine_id,
            proving_cost,
            proving_cycles,
          }) => (
            <div className="space-y-4 border-b py-4" key={proof_id}>
              <div className="flex items-center">
                <div className="grid max-h-20 place-items-center">
                  {prover_machine_id && (
                    <Image
                      src={getProverLogoSrc(prover_machine_id)}
                      width={128} // TODO: Fix dynamic aspect ratio
                      height={80}
                      alt="Prover logo"
                    />
                  )}
                </div>
                <Button
                  variant="outline"
                  className="ms-auto h-8 w-8 gap-2 text-2xl text-primary md:w-fit"
                >
                  <ArrowDown />
                  <span className="text-xs font-bold max-md:hidden">
                    Download proof
                  </span>
                </Button>
              </div>
              <div className="grid grid-cols-2 gap-x-2 gap-y-6 md:grid-cols-4 lg:grid-cols-5">
                <div>
                  <div className="text-body-secondary">Time to proof</div>
                  <div className="text-2xl">{prover_duration as string}</div>
                </div>
                <div className="grid grid-cols-2 gap-x-2 gap-y-6 md:grid-cols-4 lg:grid-cols-5">
                  <div>
                    <div className="text-body-secondary">Time to proof</div>
                    <div className="text-2xl">{prover_duration as string}</div>
                  </div>
                  <div>
                    <div className="text-body-secondary">Latency</div>
                    <div className="text-2xl">
                      {formatNumber(
                        intervalToSeconds(prover_duration as string),
                        {
                          style: "unit",
                          unit: "second",
                          unitDisplay: "narrow",
                        }
                      )}
                    </div>
                  </div>
                  <div>
                    <div className="text-body-secondary">zkVM cycles</div>
                    <div className="text-2xl">
                      {proving_cycles
                        ? formatNumber(proving_cycles, {
                            // notation: "compact",
                            // compactDisplay: "short",
                          })
                        : ""}
                    </div>
                  </div>
                  <div>
                    <div className="text-body-secondary">Proving cost</div>
                    <div className="text-2xl">
                      {/* TODO: Confirm cost unit */}
                      {proving_cost
                        ? formatNumber(proving_cost, {
                            style: "currency",
                            currency: "USD",
                          })
                        : ""}
                    </div>
                  </div>
                </div>
              </div>
            </div>
          )
        )}
      </section>

      <LearnMore />
    </div>
  )
}
