CREATE TABLE "cluster_machines" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "cluster_machines_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"gpu_models" text[] NOT NULL,
	"memory_gb" integer NOT NULL,
	"memory_specification" text NOT NULL,
	"network_configuration" text,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
ALTER TABLE "cluster_machines" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
ALTER TABLE "cluster_configurations" ADD COLUMN "cluster_machine_id" bigint;--> statement-breakpoint
ALTER TABLE "cluster_configurations" ADD COLUMN "cluster_machine_count" smallint;--> statement-breakpoint
ALTER TABLE "cluster_configurations" ADD CONSTRAINT "cluster_configurations_cluster_machine_id_cluster_machines_id_fk" FOREIGN KEY ("cluster_machine_id") REFERENCES "public"."cluster_machines"("id") ON DELETE cascade ON UPDATE cascade;--> statement-breakpoint
CREATE POLICY "Enable read access for all users" ON "cluster_machines" AS PERMISSIVE FOR SELECT TO public USING (true);--> statement-breakpoint
CREATE POLICY "Enable insert for users with an api key" ON "cluster_machines" AS PERMISSIVE FOR INSERT TO public;