CREATE TABLE "proofs_daily_stats" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "proofs_daily_stats_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"date" timestamp with time zone NOT NULL,
	"avg_cost" double precision NOT NULL,
	"median_cost" double precision NOT NULL,
	"avg_latency" integer NOT NULL,
	"median_latency" integer NOT NULL,
	"total_proofs" integer NOT NULL,
	CONSTRAINT "proofs_daily_stats_date_key" UNIQUE("date")
);
ALTER TABLE "proofs_daily_stats" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
--> statement-breakpoint
CREATE TABLE "prover_daily_stats" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "prover_daily_stats_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"date" timestamp with time zone NOT NULL,
	"team_id" uuid NOT NULL,
	"avg_cost" double precision NOT NULL,
	"median_cost" double precision NOT NULL,
	"avg_latency" integer NOT NULL,
	"median_latency" integer NOT NULL,
	"total_proofs" integer NOT NULL,
	CONSTRAINT "prover_daily_stats_date_team_key" UNIQUE("date","team_id")
);
ALTER TABLE "prover_daily_stats" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
ALTER TABLE "prover_daily_stats" ADD CONSTRAINT "prover_daily_stats_team_id_teams_id_fk" FOREIGN KEY ("team_id") REFERENCES "public"."teams"("id") ON DELETE cascade ON UPDATE cascade;--> statement-breakpoint
