CREATE TABLE IF NOT EXISTS "gpu_price_index" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "gpu_price_index_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"gpu_name" text NOT NULL,
	"hourly_price" numeric(10, 6) NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL
);

-- Add unique constraint to prevent duplicate (gpu_name, created_at) entries
CREATE UNIQUE INDEX IF NOT EXISTS "gpu_price_index_gpu_name_created_at_unique"
  ON "gpu_price_index" ("gpu_name", "created_at");
