-- Create guest_programs table
CREATE TABLE IF NOT EXISTS "guest_programs" (
  "id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  "name" text NOT NULL,
  "language" text NOT NULL,
  "maintainer" text NOT NULL,
  "ecosystem" text NOT NULL,
  "license" text NOT NULL,
  "repo_url" text NOT NULL,
  "created_at" timestamp with time zone DEFAULT now() NOT NULL
);

-- Enable RLS on guest_programs
ALTER TABLE "guest_programs" ENABLE ROW LEVEL SECURITY;

-- Create read policy for guest_programs
CREATE POLICY "Enable read access for all users" ON "guest_programs"
  AS PERMISSIVE FOR SELECT TO public USING (true);

-- Add guest_program_id column to clusters table
ALTER TABLE "clusters" ADD COLUMN "guest_program_id" bigint;

-- Add foreign key constraint
ALTER TABLE "clusters" ADD CONSTRAINT "clusters_guest_program_id_guest_programs_id_fk"
  FOREIGN KEY ("guest_program_id") REFERENCES "guest_programs"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- Populate guest_programs with initial data
INSERT INTO "guest_programs" ("name", "language", "maintainer", "ecosystem", "license", "repo_url") VALUES
  ('revm', 'Rust', 'Tempo', 'Ethereum L1', 'MIT', 'https://github.com/bluealloy/revm'),
  ('levm', 'Rust', 'LambdaClass', 'Ethereum L1', 'Apache 2.0', 'https://github.com/lambdaclass/ethrex/tree/main/crates/vm/levm'),
  ('evmone', 'C++', 'Ipsilon', 'Ethereum L1', 'Apache 2.0', 'https://github.com/ipsilon/evmone'),
  ('ZKsync OS', 'Rust', 'Matter Labs', 'ZKsync L2', 'Apache 2.0; MIT', 'https://github.com/matter-labs/zksync-os/tree/main/evm_interpreter');

-- Backfill guest_program_id for active clusters based on name patterns
UPDATE "clusters" SET "guest_program_id" = (
  SELECT "id" FROM "guest_programs" WHERE "name" = 'ZKsync OS'
) WHERE "is_active" = true AND "name" ILIKE '%Airbender%';

UPDATE "clusters" SET "guest_program_id" = (
  SELECT "id" FROM "guest_programs" WHERE "name" = 'levm'
) WHERE "is_active" = true AND "name" ILIKE '%Ethrex%';

UPDATE "clusters" SET "guest_program_id" = (
  SELECT "id" FROM "guest_programs" WHERE "name" = 'evmone'
) WHERE "is_active" = true AND "name" ILIKE '%zilkworm%';

-- Default all other active clusters to revm
UPDATE "clusters" SET "guest_program_id" = (
  SELECT "id" FROM "guest_programs" WHERE "name" = 'revm'
) WHERE "is_active" = true AND "guest_program_id" IS NULL;
