CREATE TABLE IF NOT EXISTS "rtp_cohort_snapshots" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
	"cluster_id" uuid NOT NULL,
	"snapshot_week" timestamp with time zone NOT NULL,
	"total_blocks" integer NOT NULL,
	"blocks_proven" integer NOT NULL,
	"sub_10s_proofs" integer NOT NULL,
	"over_10s_proofs" integer NOT NULL,
	"paralyzed_blocks" integer NOT NULL,
	"performance_score" double precision NOT NULL,
	"liveness_score" double precision NOT NULL,
	"stunner_rate" double precision NOT NULL,
	"paralyzer_rate" double precision NOT NULL,
	"is_eligible" boolean DEFAULT false NOT NULL,
	"avg_cost_per_proof" double precision,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL
);

ALTER TABLE "rtp_cohort_snapshots" ADD CONSTRAINT "rtp_cohort_snapshots_cluster_id_clusters_id_fk" FOREIGN KEY ("cluster_id") REFERENCES "public"."clusters"("id") ON DELETE cascade ON UPDATE cascade;

ALTER TABLE "rtp_cohort_snapshots" ADD CONSTRAINT "rtp_cohort_snapshots_cluster_id_snapshot_week_uk" UNIQUE("cluster_id","snapshot_week");

CREATE INDEX IF NOT EXISTS "rtp_cohort_snapshots_cluster_id_idx" ON "rtp_cohort_snapshots" USING btree ("cluster_id");
CREATE INDEX IF NOT EXISTS "rtp_cohort_snapshots_snapshot_week_idx" ON "rtp_cohort_snapshots" USING btree ("snapshot_week");

ALTER TABLE "rtp_cohort_snapshots" ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Enable read access for all users" ON "rtp_cohort_snapshots" AS PERMISSIVE FOR SELECT TO public USING (true);
