CREATE TABLE IF NOT EXISTS gpu_price_pending_requests (
    id bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    request_id bigint NOT NULL,
    created_at timestamptz DEFAULT now() NOT NULL
);

CREATE OR REPLACE FUNCTION request_gpu_price_update()
RETURNS void
LANGUAGE plpgsql
SECURITY DEFINER
AS $$
DECLARE
    api_key TEXT;
    req_id BIGINT;
    gpu_model TEXT := 'RTX 5090';
BEGIN
    api_key := get_vastai_api_key();

    IF api_key IS NULL THEN
        RAISE LOG 'Vast.ai API key not found. Skipping GPU price request.';
        RETURN;
    END IF;

    RAISE LOG 'Queuing GPU price request for %...', gpu_model;

    SELECT net.http_post(
        url := 'https://console.vast.ai/api/v0/bundles/',
        headers := jsonb_build_object(
            'Authorization', api_key,
            'Content-Type', 'application/json'
        ),
        body := jsonb_build_object(
            'limit', 100,
            'type', 'on-demand',
            'verified', jsonb_build_object('eq', true),
            'gpu_name', jsonb_build_object('eq', gpu_model)
        )
    ) INTO req_id;

    INSERT INTO gpu_price_pending_requests (request_id) VALUES (req_id);

    RAISE LOG 'GPU price request queued with ID: %', req_id;
END;
$$;

CREATE OR REPLACE FUNCTION process_gpu_price_response()
RETURNS void
LANGUAGE plpgsql
SECURITY DEFINER
AS $$
DECLARE
    pending RECORD;
    response_record RECORD;
    response_body JSONB;
    prices NUMERIC[];
    median_price NUMERIC;
    gpu_model TEXT := 'RTX 5090';
BEGIN
    FOR pending IN
        SELECT id, request_id FROM gpu_price_pending_requests
        ORDER BY created_at ASC
    LOOP
        SELECT * INTO response_record
        FROM net._http_response
        WHERE id = pending.request_id;

        IF response_record.id IS NULL THEN
            RAISE LOG 'GPU price request % still pending', pending.request_id;
            CONTINUE;
        END IF;

        DELETE FROM gpu_price_pending_requests WHERE id = pending.id;

        IF response_record.status_code != 200 THEN
            RAISE LOG 'Vast.ai API request % failed with status %: %',
                pending.request_id, response_record.status_code, response_record.content;
            CONTINUE;
        END IF;

        response_body := response_record.content::jsonb;

        IF response_body IS NULL OR NOT (response_body ? 'offers')
            OR jsonb_typeof(response_body->'offers') != 'array' THEN
            RAISE LOG 'Invalid response structure for request %', pending.request_id;
            CONTINUE;
        END IF;

        SELECT array_agg((offer->>'dph_total')::numeric)
        INTO prices
        FROM jsonb_array_elements(response_body->'offers') AS offer
        WHERE offer->>'dph_total' IS NOT NULL;

        IF prices IS NULL OR array_length(prices, 1) = 0 THEN
            RAISE LOG 'No prices found for % in request %', gpu_model, pending.request_id;
            CONTINUE;
        END IF;

        SELECT percentile_cont(0.5) WITHIN GROUP (ORDER BY price)
        INTO median_price
        FROM unnest(prices) AS price;

        INSERT INTO gpu_price_index (gpu_name, hourly_price)
        VALUES (gpu_model, median_price);

        RAISE LOG 'Inserted GPU price for %: $%/hour from % offers',
            gpu_model, median_price, array_length(prices, 1);
    END LOOP;

EXCEPTION
    WHEN OTHERS THEN
        RAISE LOG 'Error processing GPU price response: %', SQLERRM;
END;
$$;

DROP FUNCTION IF EXISTS update_gpu_price_index();

SELECT cron.unschedule(jobid)
FROM cron.job
WHERE jobname = 'update-gpu-price-index-weekly';

SELECT cron.schedule(
    'gpu-price-request-weekly',
    '0 0 * * 1',
    'SELECT request_gpu_price_update();'
);

SELECT cron.schedule(
    'gpu-price-process-weekly',
    '2 0 * * 1',
    'SELECT process_gpu_price_response();'
);
