CREATE TABLE IF NOT EXISTS "downtime_incidents" (
  "id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  "description" text NOT NULL,
  "start_block" bigint NOT NULL,
  "end_block" bigint NOT NULL,
  "created_at" timestamp with time zone DEFAULT now() NOT NULL,
  CONSTRAINT "downtime_incidents_block_range_check" CHECK ("start_block" <= "end_block")
);

ALTER TABLE "downtime_incidents" ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Enable read access for all users" ON "downtime_incidents"
  AS PERMISSIVE FOR SELECT TO public USING (true);

CREATE OR REPLACE FUNCTION is_downtime_block(p_block_number bigint)
RETURNS boolean
LANGUAGE sql STABLE
AS $$
  SELECT EXISTS (
    SELECT 1 FROM downtime_incidents di
    WHERE p_block_number BETWEEN di.start_block AND di.end_block
  );
$$;
