CREATE TABLE IF NOT EXISTS "opp_cohort_snapshots" (
  "id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  "cluster_id" uuid NOT NULL REFERENCES "clusters"("id") ON DELETE CASCADE ON UPDATE CASCADE,
  "snapshot_week" timestamp with time zone NOT NULL,
  "total_blocks" integer NOT NULL,
  "blocks_proven" integer NOT NULL,
  "sub_threshold_proofs" integer NOT NULL,
  "over_threshold_proofs" integer NOT NULL,
  "paralyzed_blocks" integer NOT NULL,
  "performance_score" double precision NOT NULL,
  "liveness_score" double precision NOT NULL,
  "stunner_rate" double precision NOT NULL,
  "paralyzer_rate" double precision NOT NULL,
  "is_eligible" boolean NOT NULL DEFAULT false,
  "avg_cost_per_proof" double precision,
  "created_at" timestamp with time zone DEFAULT now() NOT NULL,
  CONSTRAINT "opp_cohort_snapshots_cluster_id_snapshot_week_uk" UNIQUE("cluster_id", "snapshot_week")
);

CREATE INDEX IF NOT EXISTS "opp_cohort_snapshots_cluster_id_idx" ON "opp_cohort_snapshots" ("cluster_id");
CREATE INDEX IF NOT EXISTS "opp_cohort_snapshots_snapshot_week_idx" ON "opp_cohort_snapshots" ("snapshot_week");

ALTER TABLE "opp_cohort_snapshots" ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Enable read access for all users" ON "opp_cohort_snapshots"
  AS PERMISSIVE FOR SELECT TO public USING (true);
